### ISSUE TITLE
Update dependency 🙏

### ISSUE THREAD

**Issue by drbh** [grippy/redis-streams-rs#12]
the redis-rs dependency is out of date
```
redis = "0.11.0"
```
should be updated to
```
redis = "0.15.1"
```

Otherwise it causes conflict with any top level binary/library that wants to use the most up to date redis-rs

**Comment by Terkwood** [comment]
I've raised a pull request to solve this issue in #13.

**Comment by grippy** [comment]
@drbh Right on! Just published the new release: https://crates.io/crates/redis-streams
